version: "3.8"
services:
  postgresqldb:
    image: postgres
    container_name: postgresqldb
    mem_reservation: 1G
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kasyra123
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    networks:
      - postgres_network
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tests@gmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8889:80"
    networks:
      - postgres_network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:

networks:
  postgres_network:
    driver: bridge
