spring:

server:
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    org.springframework.security: DEBUG

    lt:
      code:
        samples:
          maven:
            config: debug
            security:
              filter: trace
