spring:
  messages:
    encoding: UTF-8

server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      tracking-modes: cookie
logging:
  level:
    org.springframework.security: DEBUG

    lt:
      code:
        samples:
          maven:
            config: debug
            security:
              filter: trace
